# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/eda-labs/openapi/v25.4.1/apps/bootstrap.eda.nokia.com/v1alpha1/bootstrap.json
#   timestamp: 2025-05-07T11:43:19+00:00
