# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/eda-labs/openapi/v24.12.1/apps/bootstrap.eda.nokia.com/v1alpha1/bootstrap.json
#   timestamp: 2025-01-29T15:18:34+00:00
