# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/eda-labs/openapi/v24.12.1/apps/services.eda.nokia.com/v1alpha1/services.json
#   timestamp: 2025-01-29T15:18:52+00:00
