# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/eda-labs/openapi/v25.4.1/apps/routing.eda.nokia.com/v1alpha1/routing.json

from __future__ import annotations
from typing import Annotated, Dict, List, Literal, Optional
from pydantic import BaseModel, Field, RootModel
from datetime import date


class Bfd(BaseModel):
    """
    Enable or disable BFD on this DefaultInterface.
    """

    desiredMinTransmitInt: Annotated[
        int,
        Field(
            description="The minimum interval in microseconds between transmission of BFD control packets[default=1000000].",
            ge=10000,
            le=100000000,
            title="Transmit Interval",
        ),
    ]
    detectionMultiplier: Annotated[
        int,
        Field(
            description="The number of packets that must be missed to declare this session as down. [default=3]",
            ge=3,
            le=20,
            title="Multiplier",
        ),
    ]
    enabled: Annotated[
        bool,
        Field(
            description="Enable Biforward Detection[default=false].", title="Enabled"
        ),
    ]
    minEchoReceiveInterval: Annotated[
        int,
        Field(
            description="The minimum interval between echo packets the local node can receive in microseconds",
            ge=0,
            le=100000000,
            title="Minimum Echo Receive Interval",
        ),
    ]
    requiredMinReceive: Annotated[
        int,
        Field(
            description="The minimum interval in microseconds between received BFD control packets that this system should support.[default=1000000].",
            ge=10000,
            le=100000000,
            title="Receive Interval",
        ),
    ]


class BfdModel(BaseModel):
    """
    Enable or disable BFD on this SystemInterface.
    """

    desiredMinTransmitInt: Annotated[
        int,
        Field(
            description="The minimum interval in microseconds between transmission of BFD control packets[default=1000000].",
            ge=10000,
            le=100000000,
            title="Transmit Interval",
        ),
    ]
    detectionMultiplier: Annotated[
        int,
        Field(
            description="The number of packets that must be missed to declare this session as down. [default=3]",
            ge=3,
            le=20,
            title="Multiplier",
        ),
    ]
    enabled: Annotated[
        bool,
        Field(
            description="Enable Biforward Detection[default=false].", title="Enabled"
        ),
    ]
    minEchoReceiveInterval: Annotated[
        int,
        Field(
            description="The minimum interval between echo packets the local node can receive in microseconds",
            ge=0,
            le=100000000,
            title="Minimum Echo Receive Interval",
        ),
    ]
    requiredMinReceive: Annotated[
        int,
        Field(
            description="The minimum interval in microseconds between received BFD control packets that this system should support.[default=1000000].",
            ge=10000,
            le=100000000,
            title="Receive Interval",
        ),
    ]


class Bgp(BaseModel):
    """
    BGP configuration.
    """

    autonomousSystem: Annotated[
        Optional[int],
        Field(
            description="Autonomous System number for BGP.",
            ge=1,
            le=4294967295,
            title="Autonomous System",
        ),
    ] = None
    ebgpPreference: Annotated[
        Optional[int],
        Field(
            description="Preference to be set for eBGP.",
            ge=1,
            le=255,
            title="eBGP Preference",
        ),
    ] = 170
    enabled: Annotated[
        Optional[bool],
        Field(description="Enables BGP in the default VRF.", title="Enable BGP"),
    ] = False
    ibgpPreference: Annotated[
        Optional[int],
        Field(
            description="Preference to be set for iBGP.",
            ge=1,
            le=255,
            title="iBGP Preference",
        ),
    ] = 170
    ipv4Unicast: Annotated[
        Optional[Ipv4Unicast],
        Field(
            description="Parameters relating to the IPv4 unicast AFI/SAFI.",
            title="IPv4 Unicast",
        ),
    ] = None
    ipv6Unicast: Annotated[
        Optional[Ipv6Unicast],
        Field(
            description="Parameters relating to the IPv6 unicast AFI/SAFI.",
            title="IPv6 Unicast",
        ),
    ] = None
    keychain: Annotated[
        Optional[str],
        Field(description="Keychain to be used for authentication", title="Keychain"),
    ] = None
    l2VPNEVPN: Annotated[
        Optional[L2VPNEVPN],
        Field(
            description="Parameters relating to the EVPN AFI/SAFI.", title="L2VPN EVPN"
        ),
    ] = None
    minWaitToAdvertise: Annotated[
        Optional[int],
        Field(
            description="Minimum wait time before advertising routes post BGP restart.",
            ge=0,
            le=3600,
            title="Min Wait To Advertise Time",
        ),
    ] = 0
    rapidWithdrawl: Annotated[
        Optional[bool],
        Field(
            description="Enable rapid withdrawal in BGP.",
            title="Enable Rapid Withdrawal",
        ),
    ] = False
    sendCommunityLarge: Annotated[
        Optional[bool],
        Field(
            description="When false, all large (12 byte) BGP communities from all outbound routes advertised to the peer are stripped.",
            title="Send Community Large",
        ),
    ] = None
    sendCommunityStandard: Annotated[
        Optional[bool],
        Field(
            description="When false, all standard (4 byte) communities from all outbound routes advertised to the peer are stripped.",
            title="Send Community Standard",
        ),
    ] = None
    waitForFibInstall: Annotated[
        Optional[bool],
        Field(
            description="Wait for FIB installation before advertising routes.",
            title="Wait for FIB Installation",
        ),
    ] = False


class DefaultInterface(BaseModel):
    """
    DefaultInterface is the Schema for the defaultinterfaces API
    """

    apiVersion: str
    kind: str
    metadata: DefaultInterfaceMetadata
    spec: Annotated[
        Spec,
        Field(
            description="DefaultInterface enables the configuration of default interfaces, including Interface references, DefaultRouter, VLAN IDs, IP MTU settings, and options for IPv4 and IPv6 addresses. It also supports unnumbered interfaces and BFD (Bidirectional Forwarding Detection) configuration.",
            title="Specification",
        ),
    ]
    status: Annotated[
        Optional[Status],
        Field(
            description="DefaultInterfaceStatus defines the observed state of DefaultInterface",
            title="Status",
        ),
    ] = None


class DefaultInterfaceDeletedResourceEntry(BaseModel):
    commitTime: Optional[str] = None
    hash: Optional[str] = None
    name: Optional[str] = None
    namespace: Optional[str] = None
    transactionId: Optional[int] = None


class DefaultInterfaceDeletedResources(
    RootModel[List[DefaultInterfaceDeletedResourceEntry]]
):
    root: List[DefaultInterfaceDeletedResourceEntry]


class DefaultInterfaceList(BaseModel):
    """
    DefaultInterfaceList is a list of defaultinterfaces
    """

    apiVersion: str
    items: Optional[List[DefaultInterface]] = None
    kind: str


class DefaultInterfaceMetadata(BaseModel):
    annotations: Optional[Dict[str, str]] = None
    labels: Optional[Dict[str, str]] = None
    name: Annotated[
        str,
        Field(
            max_length=253,
            pattern="^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$",
        ),
    ]
    namespace: str


class DefaultRouter(BaseModel):
    """
    DefaultRouter is the Schema for the defaultrouters API
    """

    apiVersion: str
    kind: str
    metadata: DefaultRouterMetadata
    spec: Annotated[
        SpecModel,
        Field(
            description="DefaultRouter enables the configuration of default routing instances on a specified Node, including options for BGP configuration, import and export policies, and router IDs.",
            title="Specification",
        ),
    ]
    status: Annotated[
        Optional[Status1Model],
        Field(
            description="DefaultRouterStatus defines the observed state of DefaultRouter",
            title="Status",
        ),
    ] = None


DefaultRouterDeletedResourceEntry = DefaultInterfaceDeletedResourceEntry


class DefaultRouterDeletedResources(RootModel[List[DefaultRouterDeletedResourceEntry]]):
    root: List[DefaultRouterDeletedResourceEntry]


class DefaultRouterList(BaseModel):
    """
    DefaultRouterList is a list of defaultrouters
    """

    apiVersion: str
    items: Optional[List[DefaultRouter]] = None
    kind: str


DefaultRouterMetadata = DefaultInterfaceMetadata


class Drain(BaseModel):
    """
    Drain is the Schema for the drains API
    """

    apiVersion: str
    kind: str
    metadata: DrainMetadata
    spec: Annotated[
        SpecModel1,
        Field(
            description="Drain allows for the controlled disabling or draining of specific DefaultRouters, either by selecting them through labels or directly referencing them, ensuring traffic is safely rerouted or dropped before the routers are decommissioned.",
            title="Specification",
        ),
    ]
    status: Annotated[
        Optional[Status1Model1],
        Field(
            description="DrainStatus defines the observed state of Drain.",
            title="Status",
        ),
    ] = None


DrainDeletedResourceEntry = DefaultInterfaceDeletedResourceEntry


class DrainDeletedResources(RootModel[List[DrainDeletedResourceEntry]]):
    root: List[DrainDeletedResourceEntry]


class DrainList(BaseModel):
    """
    DrainList is a list of drains
    """

    apiVersion: str
    items: Optional[List[Drain]] = None
    kind: str


DrainMetadata = DefaultInterfaceMetadata


class Ipv4Address(BaseModel):
    ipPrefix: Annotated[
        str, Field(description="Address and mask to use", title="IP Prefix")
    ]
    primary: Annotated[
        Optional[bool],
        Field(
            description="Indicates which address to use as primary for broadcast",
            title="Primary",
        ),
    ] = None


class Ipv4Unicast(BaseModel):
    """
    Parameters relating to the IPv4 unicast AFI/SAFI.
    """

    advertiseIPV6NextHops: Annotated[
        Optional[bool],
        Field(
            description="Enables advertisement of IPv4 Unicast routes with IPv6 next-hops to peers.",
            title="Advertise IPv6 Next Hops",
        ),
    ] = None
    enabled: Annotated[
        Optional[bool],
        Field(description="Enables the IPv4 unicast AFISAFI.", title="Enabled"),
    ] = None
    multipath: Annotated[
        Optional[Multipath], Field(description="Enable multipath.", title="Multipath")
    ] = None
    rapidUpdate: Annotated[
        Optional[bool], Field(description="Enables rapid update.", title="Rapid Update")
    ] = None
    receiveIPV6NextHops: Annotated[
        Optional[bool],
        Field(
            description="Enables the advertisement of the RFC 5549 capability to receive IPv4 routes with IPv6 next-hops.",
            title="Receive IPv6 Next Hops",
        ),
    ] = None


Ipv6Address = Ipv4Address


class Ipv6Unicast(BaseModel):
    """
    Parameters relating to the IPv6 unicast AFI/SAFI.
    """

    enabled: Annotated[
        Optional[bool],
        Field(description="Enables the IPv6 unicast AFISAFI", title="Enabled"),
    ] = None
    multipath: Annotated[
        Optional[MultipathModel],
        Field(description="Enable multipath", title="Multipath"),
    ] = None
    rapidUpdate: Annotated[
        Optional[bool], Field(description="Enables rapid update.", title="Rapid Update")
    ] = None


class L2VPNEVPN(BaseModel):
    """
    Parameters relating to the EVPN AFI/SAFI.
    """

    advertiseIPV6NextHops: Annotated[
        Optional[bool],
        Field(
            description="Enables advertisement of EVPN routes with IPv6 next-hops to peers.",
            title="Advertise IPv6 Next Hops",
        ),
    ] = None
    enabled: Annotated[
        Optional[bool],
        Field(description="Enables the L2VPN EVPN AFISAFI.", title="Enabled"),
    ] = None
    interASVPN: Annotated[
        Optional[bool],
        Field(description="Enable inter-AS VPN for EVPN.", title="EVPN InterAS VPN"),
    ] = False
    multipath: Annotated[
        Optional[MultipathModel],
        Field(description="Enable multipath", title="Multipath"),
    ] = None
    rapidUpdate: Annotated[
        Optional[bool], Field(description="Enables rapid update.", title="Rapid Update")
    ] = None


class Multipath(BaseModel):
    """
    Enable multipath.
    """

    allowMultipleAS: Annotated[
        bool,
        Field(
            description="When set to true, BGP is allowed to build a multipath set using BGP routes with different neighbor AS (most recent AS in the AS_PATH), When set to false, BGP is only allowed to use non-best paths for ECMP if they meet the multipath criteria and they have the same neighbor AS as the best path.",
            title="Allow Multiple Autonomous Systems Per Path",
        ),
    ]
    maxAllowedPaths: Annotated[
        int,
        Field(
            description="The maximum number of BGP ECMP next-hops for BGP routes with an NLRI belonging to the address family of this configuration context.",
            ge=1,
            le=256,
            title="Maximum Number of Paths",
        ),
    ]


class MultipathModel(BaseModel):
    """
    Enable multipath
    """

    allowMultipleAS: Annotated[
        bool,
        Field(
            description="When set to true, BGP is allowed to build a multipath set using BGP routes with different neighbor AS (most recent AS in the AS_PATH), When set to false, BGP is only allowed to use non-best paths for ECMP if they meet the multipath criteria and they have the same neighbor AS as the best path.",
            title="Allow Multiple Autonomous Systems Per Path",
        ),
    ]
    maxAllowedPaths: Annotated[
        int,
        Field(
            description="The maximum number of BGP ECMP next-hops for BGP routes with an NLRI belonging to the address family of this configuration context.",
            ge=1,
            le=256,
            title="Maximum Number of Paths",
        ),
    ]


class RouteLeaking(BaseModel):
    """
    Route leaking controlled by routing policies in and out of the DefaultRouter.
    """

    exportPolicy: Annotated[
        str,
        Field(
            description="Reference to a Policy resource to use when evaluating route exports from the DefaultRouter.",
            title="Export Policy",
        ),
    ]
    importPolicy: Annotated[
        str,
        Field(
            description="Reference to a Policy resource to use when evaluating route imports into the DefaultRouter.",
            title="Import Policy",
        ),
    ]


class Spec(BaseModel):
    """
    DefaultInterface enables the configuration of default interfaces, including Interface references, DefaultRouter, VLAN IDs, IP MTU settings, and options for IPv4 and IPv6 addresses. It also supports unnumbered interfaces and BFD (Bidirectional Forwarding Detection) configuration.
    """

    bfd: Annotated[
        Optional[Bfd],
        Field(
            description="Enable or disable BFD on this DefaultInterface.",
            title="BFD Configuration",
        ),
    ] = None
    defaultRouter: Annotated[
        str, Field(description="Reference to a DefaultRouter.", title="Default Router")
    ]
    interface: Annotated[
        str,
        Field(
            description="Reference to an Interface to use for attachment.",
            title="Interface Reference",
        ),
    ]
    ipMTU: Annotated[
        Optional[int],
        Field(
            description="Set the IP MTU for the DefaultInterface.",
            ge=1280,
            le=9486,
            title="IP MTU",
        ),
    ] = None
    ipv4Addresses: Annotated[
        Optional[List[Ipv4Address]],
        Field(
            description="List of IPv4 addresses in ip/mask form, e.g., 192.168.0.1/24.",
            title="IPv4 Addresses",
        ),
    ] = None
    ipv6Addresses: Annotated[
        Optional[List[Ipv6Address]],
        Field(
            description="List of IPv6 addresses in ip/mask form, e.g., fc00::1/120.",
            title="IPv6 Addresses",
        ),
    ] = None
    unnumbered: Annotated[
        Optional[Literal["IPV6"]],
        Field(
            description="Enables the use of unnumbered interfaces on the ISL. For IPv6, no IP address are configured on the sub-interface and only the link local address will be used. If any allocation pool is specified for IPv6 that will take precedence and IPs will be assigned to the interfaces.  When using eBGP for an underlay protocol, the DefaultInterfaces which are a part of the ISL will be added to the BGP dynamic neighbor list.",
            title="Unnumbered",
        ),
    ] = None
    vlanID: Annotated[
        Optional[int],
        Field(
            description="VLAN to use with this DefaultInterface.",
            ge=1,
            le=4094,
            title="VLAN ID",
        ),
    ] = None


class SpecModel(BaseModel):
    """
    DefaultRouter enables the configuration of default routing instances on a specified Node, including options for BGP configuration, import and export policies, and router IDs.
    """

    bgp: Annotated[
        Optional[Bgp],
        Field(description="BGP configuration.", title="BGP Configuration"),
    ] = None
    description: Annotated[
        Optional[str],
        Field(
            description="Sets the description on the Default router.",
            title="Description",
        ),
    ] = None
    exportPolicy: Annotated[
        Optional[List[str]],
        Field(
            description="Reference to a Policy resource to use when evaluating route exports from the DefaultRouter.",
            title="Export Policy",
        ),
    ] = None
    importPolicy: Annotated[
        Optional[List[str]],
        Field(
            description="Reference to a Policy resource to use when evaluating route imports into the DefaultRouter.",
            title="Import Policy",
        ),
    ] = None
    node: Annotated[
        str,
        Field(
            description="Reference to a TopoNode on which to configure the default routing instance.",
            title="Node",
        ),
    ]
    routeLeaking: Annotated[
        Optional[RouteLeaking],
        Field(
            description="Route leaking controlled by routing policies in and out of the DefaultRouter.",
            title="Route Leaking",
        ),
    ] = None
    routerID: Annotated[
        str, Field(description="Router ID in dotted quad notation.", title="Router ID")
    ]


class SpecModel1(BaseModel):
    """
    Drain allows for the controlled disabling or draining of specific DefaultRouters, either by selecting them through labels or directly referencing them, ensuring traffic is safely rerouted or dropped before the routers are decommissioned.
    """

    defaultRouterSelector: Annotated[
        Optional[List[str]],
        Field(
            description="Selector to use when selecting DefaultRouters to drain.",
            title="Default Router Selector",
        ),
    ] = None
    defaultRouters: Annotated[
        Optional[List[str]],
        Field(
            description="Reference to DefaultRouters to drain.", title="Default Routers"
        ),
    ] = None
    enabled: Annotated[
        Optional[bool], Field(description="Enable this Drain.", title="Enabled")
    ] = True


class SpecModel2(BaseModel):
    """
    SystemInterfaceSpec defines the desired state of SystemInterface
    """

    bfd: Annotated[
        Optional[BfdModel],
        Field(
            description="Enable or disable BFD on this SystemInterface.",
            title="BFD Configuration",
        ),
    ] = None
    defaultRouter: Annotated[
        str, Field(description="Reference to a DefaultRouter.", title="Default Router")
    ]
    ipv4Address: Annotated[
        Optional[str],
        Field(
            description="IPv4 address in ip/mask form, e.g., 192.168.0.1/32.",
            title="IPv4 Address",
        ),
    ] = None
    ipv6Address: Annotated[
        Optional[str],
        Field(
            description="IPv6 address in ip/mask form, e.g., fc00::1/128.",
            title="IPv6 Address",
        ),
    ] = None


class Status(BaseModel):
    """
    DefaultInterfaceStatus defines the observed state of DefaultInterface
    """

    health: Annotated[
        Optional[int],
        Field(
            description="Indicates the health score of the DefaultInterface.",
            title="Health",
        ),
    ] = None
    healthScoreReason: Annotated[
        Optional[str],
        Field(
            description="Indicates the reason for the health score.",
            title="Health Score Reason",
        ),
    ] = None
    lastChange: Annotated[
        Optional[date],
        Field(
            description="Indicates when this Interface last changed state.",
            title="Last Change",
        ),
    ] = None
    operationalState: Annotated[
        Optional[str],
        Field(
            description="Indicates the current operational state of the DefaultInterface.",
            title="Operational State",
        ),
    ] = None


class Status1Model(BaseModel):
    """
    DefaultRouterStatus defines the observed state of DefaultRouter
    """

    health: Annotated[
        Optional[int],
        Field(description="Indicates the health score of the Router.", title="Health"),
    ] = None
    healthScoreReason: Annotated[
        Optional[str],
        Field(
            description="Indicates the reason for the health score.",
            title="Health Score Reason",
        ),
    ] = None
    lastChange: Annotated[
        Optional[date],
        Field(
            description="The time when the state of the resource last changed.",
            title="Last Change",
        ),
    ] = None
    operationalState: Annotated[
        Optional[str],
        Field(
            description="Operational state of the Router.", title="Operational State"
        ),
    ] = None


class Status1Model1(BaseModel):
    """
    DrainStatus defines the observed state of Drain.
    """

    defaultRouters: Annotated[
        Optional[List[str]],
        Field(
            description="List of DefaultRouters this Drain has been applied to",
            title="Default Routers",
        ),
    ] = None


class Status1Model2(BaseModel):
    """
    SystemInterfaceStatus defines the observed state of SystemInterface
    """

    health: Annotated[
        Optional[int],
        Field(
            description="Indicates the health score of the SystemInterface.",
            title="Health",
        ),
    ] = None
    healthScoreReason: Annotated[
        Optional[str],
        Field(
            description="Indicates the reason for the health score.",
            title="Health Score Reason",
        ),
    ] = None
    lastChange: Annotated[
        Optional[date],
        Field(
            description="Indicates when this Interface last changed state.",
            title="Last Change",
        ),
    ] = None
    operationalState: Annotated[
        Optional[str],
        Field(
            description="Indicates the current operational state of the SystemInterface.",
            title="Operational State",
        ),
    ] = None


class SystemInterface(BaseModel):
    """
    SystemInterface is the Schema for the systeminterfaces API
    """

    apiVersion: str
    kind: str
    metadata: SystemInterfaceMetadata
    spec: Annotated[
        SpecModel2,
        Field(
            description="SystemInterfaceSpec defines the desired state of SystemInterface",
            title="Specification",
        ),
    ]
    status: Annotated[
        Optional[Status1Model2],
        Field(
            description="SystemInterfaceStatus defines the observed state of SystemInterface",
            title="Status",
        ),
    ] = None


SystemInterfaceDeletedResourceEntry = DefaultInterfaceDeletedResourceEntry


class SystemInterfaceDeletedResources(
    RootModel[List[SystemInterfaceDeletedResourceEntry]]
):
    root: List[SystemInterfaceDeletedResourceEntry]


class SystemInterfaceList(BaseModel):
    """
    SystemInterfaceList is a list of systeminterfaces
    """

    apiVersion: str
    items: Optional[List[SystemInterface]] = None
    kind: str


SystemInterfaceMetadata = DefaultInterfaceMetadata
