# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/eda-labs/openapi/v25.4.1/apps/protocols.eda.nokia.com/v1alpha1/protocols.json
#   timestamp: 2025-05-07T11:43:57+00:00
