# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/eda-labs/openapi/v24.12.1/apps/siteinfo.eda.nokia.com/v1alpha1/siteinfo.json
#   timestamp: 2025-01-29T15:18:53+00:00
