# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/eda-labs/openapi/v25.4.1/apps/aifabrics.eda.nokia.com/v1alpha1/aifabrics.json
#   timestamp: 2025-05-07T11:43:13+00:00
