# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/eda-labs/openapi/v24.12.1/apps/interfaces.eda.nokia.com/v1alpha1/interfaces.json
#   timestamp: 2025-01-29T15:18:42+00:00
