# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/eda-labs/openapi/v25.4.1/apps/interfaces.eda.nokia.com/v1alpha1/interfaces.json
#   timestamp: 2025-05-07T11:43:46+00:00
